### ISSUE TITLE
Not compatible with theseoframework

### ISSUE THREAD

**Issue by extremeshok** [froger-me/wp-remote-users-sync#3] opened 2020-03-25 21:12 UTC
Results in a fatal error, when navigating to the settings page "/wp-admin/admin.php?page=wprus"

https://wordpress.org/plugins/autodescription/

https://theseoframework.com

**Comment by froger-me** [comment] 2020-04-23 00:59
Hi @extremeshok 
The plugin has been updated quite a lot - could you confirm the issue is still there? If yes, could you please indicate the exact message from PHP logs?

**Comment by froger-me** [comment] 2020-05-01 09:05
More than a week without activity - closing.

**Closed by froger-me** 2020-05-01 09:05 UTC
