### ISSUE TITLE
Best practices with WPML

### ISSUE THREAD

**Issue by mennobouma** [froger-me/wp-remote-users-sync#13] opened 2020-09-11 10:23 UTC
[From Wordpress.org]

--
Hello Alexandre,

I’m using your plugin with WPML, with one language per domain. I would like to know what the best practices are, do i need to add all languages as remote sites or only the main site and use the SSO feature of WPML?
--

I did some testing on this:

> Adding the WP install language only doesn't login the other translated domains.
> Adding the WP install AND translated domain does login both languages / sites.

So i need to add a remote site for every language. But the logout doesn't work. Please test it with these sites, both run 1.2.7-dev:

https://www.lifecloud.id/ English - WP install
https://www.lifecloud.nl/ Dutch - Translation

https://www.lifegroup.nl/my-account/ English - WP install
https://www.lifegroep.nl/mijn-account Dutch - Translation

mennolives
d*bBxwb%TjAjRPTG!dLpzQ%Q

The SSO feature of WPML doesn't work too at this moment even when it's enabled in the admin.
https://wpml.org/documentation/getting-started-guide/language-setup/passing-session-data-between-languages-in-domains/. 

I think the best scenario is that only the WP installs (English sites) need to be added as remote sites and not the languages (other domains). When you login or logout in needs to work on the wp install and the translated domains. 

I don't know for sure if a part of the issue is with your plugin or with WPML. Or a combination :).

Thanks,
Menno

**Comment by froger-me** [comment] 2020-09-11 10:36
Hi Menno,

Which browser are you testing with? It appears from the WPML source code that Safari and browsers with cross-domain cookie disabled won't allow WPML SSO, because they use iframes. Same issue as I encountered with WPRUS.

For the WPML SSO to work in all browsers (which, again, I haven't used before), that would be with subdomains only, provided the cookie domain WordPress constant `COOKIE_DOMAIN` is set to the top level domain.

**Comment by froger-me** [comment] 2020-09-11 11:02
Other question: is WPML SSO working _without_ WPRUS activated? I did see the WPML SSO call upon login on https://www.lifecloud.id ( call to https://www.lifecloud.nl/?wpml_sso_iframe_hash=[some_hash] in the iframe) but didn't get authenticated on https://www.lifecloud.nl...

**Comment by froger-me** [comment] 2020-09-11 11:39
On another note.... I think found why the other sites don't get logged in via SSO when all domains are added (in case WPML SSO worked, [which I couldn't see in action so far](https://github.com/froger-me/wp-remote-users-sync/issues/13#issuecomment-691028806))

```php
    public function iframe_ajax_sign_user() {
		$this->set_current_user_id( $this->get_user_id_from_post_var() );

		if ( $this->validate_ajax_sign_user() ) {
			$user_status = isset( $_POST['user_status'] )
				? filter_var( $_POST['user_status'], FILTER_SANITIZE_STRING ) : null;

			if ( 'wpml_is_user_signed_in' === $user_status ) {
				wp_set_auth_cookie( $this->current_user_id );
			} else {
				wp_clear_auth_cookie();
			}

			delete_transient( $this->get_domain_transient_name( $this->get_current_domain() ) );
		}
	}
```

No call to `do_action( 'wp_login' )` after `wp_set_auth_cookie( $this->current_user_id );`. I'm currently investigating a new way to handle the login without relying on the `wp_login` action hook, but that doesn't mean the question above is less important.

**Comment by mennobouma** [comment] 2020-09-11 15:43
Hello Alexandre,

Thanks for your reply. I'm testing with Google Chrome on desktop. 

I was able to login WPML on all domains by adding this to wp-config.php:

`
define('ADMIN_COOKIE_PATH', '/');
define('COOKIE_DOMAIN', '');
define('COOKIEPATH', '');
define('SITECOOKIEPATH', '');
`

But it looks like it's not working with your plugin.. Does www.lifecloud.id works at your place?

Thanks,
Menno

**Comment by froger-me** [comment] 2020-09-11 16:04
Hi Menno,

At the time of writing, logging in on https://www.lifecloud.id does not log me anywhere else ; this is a different behavior from the [previous test](https://github.com/froger-me/wp-remote-users-sync/issues/13#issuecomment-691028806), and I cannot know what settings changed (or what the totality of the settings of WPML and WPRUS across the websites are), which makes it difficult for me to draw any conclusion.

**Comment by froger-me** [comment] 2020-09-12 14:56
Testing further [before your last comment and changes of settings](https://github.com/froger-me/wp-remote-users-sync/issues/13#issuecomment-691171086) ; when logging in https://www.lifecloud.id/, I got logged in the registered websites in WPRUS:

- https://www.lifegroup.nl
- https://www.lifedeals.com
- https://www.lifejobs.nl
- https://www.lifegroep.nl

I do not know if that's all the sites registered in WPRUS, but if it is, then the WPRUS SSO is working as designed.

### After more research, here is the deal when combining WPML SSO and WPRUS SSO.

Let's take the example below:

- I log in https://www.lifecloud.id/
- I have https://www.lifegroup.nl/ as a Remote Site in WPRUS settings on https://www.lifecloud.id/, Login action in both directions
- I have https://www.lifecloud.id/ as a Remote Site in WPRUS settings on https://www.lifegroup.nl/, Login action in both directions
- we assume there are no other Remote Sites: only https://www.lifecloud.id/ and  https://www.lifegroup.nl/ are connected
- I want https://www.lifecloud.id/, https://www.lifegroup.nl/, https://www.lifecloud.nl/, and https://www.lifegroep.nl logged in as a result
- we assume WPML SSO is enabled, and working when WPRUS is enabled (basically, [this](https://github.com/froger-me/wp-remote-users-sync/issues/13#issuecomment-691028806) is solved)
- we forget Safari exists

Here is what would happen upon login:

- https://www.lifecloud.id/ loads the page ; it loads 2 iframes with minimal content only:
    - WPRUS SSO https://www.lifegroup.nl/
    - WPML SSO https://www.lifecloud.nl/
- when the page finishes loading, I get:
    - ✅ https://www.lifecloud.id/ logged in: this is the site I logged in
    - ✅ https://www.lifecloud.nl/ logged in: I got logged in via WPML loaded iframe
    - ✅ https://www.lifegroup.nl/ logged in: I got logged in via WPRUS loaded iframe
    - ❌ https://www.lifegroep.nl not logged in: nothing was output in the browser for that domain, and no cookie was set

So, https://www.lifegroep.nl couldn't set its authentication cookie ; the domain it depends on, https://www.lifegroup.nl/, had only a minimal WPRUS SSO page loaded in an iframe that didn't itself load the WPML SSO iframe.

Working around that would mean loading the full https://www.lifegroup.nl/ page in the WPRUS SSO iframe to allow for the WPML SSO https://www.lifegroep.nl iframe to load within it ; it would result in a nested iframe which would cause its own array of issues, possibly conflict with themes, and serious performances degradations.

And if we now establish Safari does exist: iframes auth cookies would not work, so we can forget about WPML SSO in Safari - I dug in the WPML code more, and I'm 99% confident it's not supported by WPML 🙁.

That's a technical limitation, not really an algorithmic issue.

## What now?

A WPRUS setup I can see working, with Login action active in both directions:

- on main-domain-1.com:
    - main-domain-2.com
    - all the language-domain-2.com
- on main-domain-2.com:
    - main-domain-1.com
    - all the language-domain-1.com

This way:

- each main-domain site handles its WPML SSO upon login, but it breaks in Safari
- each main-domain site bypasses the WPML SSO for remote domains and uses WPRUS SSO instead, because SSO within an SSO is not possible, and would break in Safari anyway

Untested, but feasible within the technical limitations of how WPML, WPRUS, SSO, browsers and the Internet in general works.

Please note that this sort of cross-browser, cross-domain, multilingual SSO with more than 3 websites is the sort of challenge even big brands such as Stackexchange still struggle with (Stackexchange's SSO does not work in Safari, for instance), and a free plugin like WPRUS in unlikely to be able to compete with such powerhouses.

**Comment by mennobouma** [comment] 2020-09-14 11:36
Hello Alexandre,

Thanks for your extensive research! 

When i add this:

`define('ADMIN_COOKIE_PATH', '/'); define('COOKIE_DOMAIN', ''); define('COOKIEPATH', ''); define('SITECOOKIEPATH', '');`

WPML works but your plugin not. I just removed it. Now your plugin should work after restart of your browser.

Your WPRUS setup looks interesting. I can e-mail you FTP and admin logins if you want. It's ok to test things at lifecloud.id and lifegroup.nl. 

I understand it's quite complex to build this with a (free) plugin. Maybe it's possible to use the REST API to build bridges between multiple WP sites. Just some thoughts :).

**Comment by froger-me** [comment] 2020-09-14 12:04
Hi Menno!

The issue is, no matters how the server is reached, it needs to set an authentication cookie in the user's browser.

This is done in only 2 ways:
- a window is loaded and sets a cookie (first party, fully cross-browser)
- an resource (iframe/scrip/img) is loaded and sets a cookie (third party, breaks in Safari/iOS and private mode browsers)

Anything else regarding _how_ it's done (REST, WPML's own brand of SSO, WPRUS's API, redirections, etc) is just decoration as far as how the Internet inner workings are concerned.

Similarly, changing cookie constants in WordPress can only affect the domain and subdomain where these constant sit: it is not possible to allow a server pointed by one domain to set a cookie for another domain.

These a technical limitations are here for security, and it's a layer hard coded in browsers. Without this, any malicious server could hijack authentication on any websites (including the most sensitive ones such as banking).

I'm going to close the issue. The suggested settings are not recommended, but simply an effort to find what is technically possible.
Would you wish I spend more time experimenting with your setup, we can discuss a fee for that, but because I don't think it's viable from a user standpoint and because I think you'd actually be able to tinker with the settings yourself, I'd feel like I'd be robbing you 😉.

**Closed by froger-me** 2020-09-14 12:04 UTC

**Comment by mennobouma** [comment] 2020-09-14 17:37
Hello Alexandre,

I think i'm going to bring all languages to the primary domain, so it's going to be www.lifecloud.id/nl etc. Then your plugin features work on all languages.

**Comment by froger-me** [comment] 2020-09-15 00:29
Indeed, that would work - using subdomains too (in which case you could make use of the WordPress cookie constants) is possible, like https://nl.lifecloud.id and the like.
Having a top domain per language is in certain cases an advantage regarding branding localization (like we see with  https://www.lifegroep.nl), but if you can get away without it, it makes the technical side of things much more workable.
