### ISSUE TITLE
Error contacting the remote site: 404 - Not Found

### ISSUE THREAD

**Issue by konsole** [froger-me/wp-remote-users-sync#2] opened 2020-03-25 01:42 UTC
After initial plugin installation, I setup matching keys on two of my websites. I also whitelisted both IPs in each site's plugin. When I try to test the login/logout/etc in the Remote Sites tab, I get "Error contacting the remote site: 404 - Not found"

The plugin looks great, but cannot seem to get the two sites (site1.website.com and site2.website.com) to connect to each other.

Any ideas of what might be causing it?

**Comment by froger-me** [comment] 2020-04-23 01:02
Hi @konsole !
There has been quite a few updates since you opened the issue - could you please confirm the problem is still happening?
If yes, could you check the plugin's log and see if there is no discrepancy in the URLs? Sometimes the WordPress settings (not the plugin's) recorded in the database are not correct (for many reasons) and it causes issues (see https://wordpress.org/support/topic/alert-login-action-is-not-activated-on-https-xxxxxxx/)

**Comment by froger-me** [comment] 2020-05-01 09:05
More than a week without activity - closing.

**Closed by froger-me** 2020-05-01 09:05 UTC
